version: '3'

services: 
    ngnix:
        build: 
            context: .
            dockerfile: ./docker/nginx.dockerfile
        image: nginx
        container_name: nginx
        ports: 
            - "80:80"
        networks: 
            - production-network
        depends_on: 
            - "node1"
            - "node2"
            - "node3"

    mongodb:
        image: mongo
        ports: 
            - "27017:27017"
        networks: 
            - production-network

    node1:
        build:
            context: .
            dockerfile: ./docker/alura-books.dockerfile
        image: douglasq/alura-books
        container_name: alura-books1
        ports: 
            - "3000"
        networks: 
            - production-network
        depends_on: 
            - "mongodb"

    node2:
        build:
            context: .
            dockerfile: ./docker/alura-books.dockerfile
        image: douglasq/alura-books
        container_name: alura-books2
        ports: 
            - "3000"
        networks: 
            - production-network
        depends_on: 
            - "mongodb"            

    node3:
        build:
            context: .
            dockerfile: ./docker/alura-books.dockerfile
        image: douglasq/alura-books
        container_name: alura-books3
        ports: 
            - "3000"
        networks: 
            - production-network
        depends_on: 
            - "mongodb"

networks: 
    production-network:
        driver: bridge